# NUMPY

In [1]:
import numpy as np

#### creating array

In [13]:
# from python list
ma_lst = [1,2,4,7,8,4,2,11,21]
arr1 = np.array(ma_lst)
print(arr1)

# generating array using range method
ma_arr = np.arange(0,101,20)
print(ma_arr)

# generating zeros
zer_arr = np.zeros((2,5))
print(zer_arr)
one_arr = np.ones(5)

#generating with linearspace
lins = np.linspace(0,20,41) #arg1 = start, arg2 = stop, arg3 = how num
print(lins)

[ 1  2  4  7  8  4  2 11 21]
[  0  20  40  60  80 100]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10.  10.5 11.  11.5 12.  12.5 13.  13.5
 14.  14.5 15.  15.5 16.  16.5 17.  17.5 18.  18.5 19.  19.5 20. ]


#### Inspecting Array

In [55]:
arr1.dtype #check data typpe
arr1.shape # check shape
arr1.size #check value size
arr.ndim #check dimension

1

#### Numpy Random

In [19]:
# random rand for uniform dist
np.random.rand(5,4) # generate a value between 0-1 the arg1 = row, arg2 =column

# random randn for normal dist
np.random.randn(10) # generate a value near the mean (0) and likely further than 0

# random randint
np.random.randint(0,100,(5,4)) # generate integer arg1 = low value inclusive, arg2 = high value exclusive, arg3 shape

array([[94, 12, 76, 33],
       [89, 73, 13,  1],
       [76, 32, 21, 98],
       [26, 84, 59, 63],
       [60, 50, 84, 25]])

In [23]:
# random seed
np.random.seed(12) #12 is an arbitrary number you can choose anynumber, this 12 is lock a random generator
np.random.rand(10)

array([0.15416284, 0.7400497 , 0.26331502, 0.53373939, 0.01457496,
       0.91874701, 0.90071485, 0.03342143, 0.95694934, 0.13720932])

#### Reshape

In [39]:
arr = np.arange(5,50)
print(arr)
arr.reshape(9,5) # you must assign them to a variable to make it a new object

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28
 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

#### Numpy Function

In [132]:
new_arr = arr.reshape(9,5)
new_arr.max()
new_arr.min()
new_arr.argmax()
new_arr.argmin() #index location
new_arr.mean()
new_arr.std()
new_arr.var()
new_arr.sum()


1215

### Selecting Data in Numpy

In [60]:
my_arr = np.arange(0,101)

In [68]:
my_arr[2]
my_arr[:90]
my_arr[5:]
my_arr[6:20]
my_arr[:-1]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [118]:
arr_2d = np.arange(0,25)
arr_2d= arr_2d.reshape(5,5)
print(arr_2d)
#select 19
arr_2d[3][-1] #or arr_2d[3,-1]
#select subset og 8,9,13,14
arr_2d[1:-2,-2:]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[ 8,  9],
       [13, 14]])

#### simple filtering

In [119]:
arr_2d[arr_2d>18]

array([19, 20, 21, 22, 23, 24])

#### modifying array

In [73]:
my_arr[:50] = 90
my_arr

array([ 90,  90,  90,  90,  90,  90,  90,  90,  90,  90,  90,  90,  90,
        90,  90,  90,  90,  90,  90,  90,  90,  90,  90,  90,  90,  90,
        90,  90,  90,  90,  90,  90,  90,  90,  90,  90,  90,  90,  90,
        90,  90,  90,  90,  90,  90,  90,  90,  90,  90,  90,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

#### Array Slicing

In [81]:
arr4 = np.arange(9,50)
new_arr4 = arr4[-10:] #this is a pointer of the original array
arr4, new_arr4
new_arr4[:] = 100
arr4 # the original array being modified

array([  9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,
        22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,
        35,  36,  37,  38,  39, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100])

#### Copy array to avoid original overriding

In [85]:
arr4 = np.arange(0,26)
new_arr4 = arr4.copy() # explicitly create a copy
new_arr4[-10:] = 100 # with this being broadcasted, it wont affect the original array
new_arr4

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

#### ARRAY OPS

In [134]:
arr5 = np.arange(0,25).reshape(5,5)
arr5 +2
arr5 * arr5
#here comes the special
arr5/arr5 #python will still run and replace the invalid div with nan value

<ipython-input-134-919cdd352ce4>:5: RuntimeWarning: invalid value encountered in true_divide
  arr5/arr5 #python will still run and replace the invalid div with nan value


array([[nan,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [ ]:
np.sqrt(arr5)
np.sin(arr5)
np.log(arr5) #this is logaritmic
np.round()

In [136]:
arr5.sum(axis=0) #across the row
arr5.sum(axis=1) #across the column

array([ 10,  35,  60,  85, 110])

#### create column in pandas

In [ ]:
df['quality'] = np.vectorize(quality)(df['total_bill'],df['tip'])

# Statistic With Numpy and Scipy

## DISTRIBUTION TYPE

#### Uniform Distribution

#### Normal Distribution

##### Difference

In [90]:
grades = [88, 82, 85, 84, 90]
mean = np.mean(grades)

difference_one = (88 - mean) **2
difference_two = (82 - mean) **2
difference_three = (85 - mean) **2
difference_four = (84 - mean) **2
difference_five = (90 - mean) **2

#Part 1: Sum the differences
difference_sum = float(difference_one + difference_two + difference_three+ difference_four + difference_five)

#Part 2: Average the differences
average_difference = difference_sum / 5
print(difference_sum)
print(mean)
print(average_difference)


40.8
85.8
8.16


##### STATISTIC FORMULA

#### STATISTIC FUNCTION 

### Determining Test Methods

### APPLICATION OF TEST METHODS

## Sample Determination Calculator

##### AB testing sample calculator

##### Baseline conversion rate

##### Desired lift

##### Splitting the sample

##### Margin of Error

##### Population Size

##### Likely sample proportion

##### using survey calculator to perform AB test

# Linear Regression

## Simple Linear Regression

In statistics, linear regression is a linear approach to modelling the relationship between a scalar response and one or more explanatory variables (also known as dependent and independent variables). The case of one explanatory variable is called simple linear regression

Summary :  
y = b0 + b1x + e  
y_hat = b0 +b1x

why is that? how that can be different ?  
e = error term  
the true y value is resulted by adding error/residual value from prediction. on the other hand, when we predicting y value in y_hat we dont know the error value until we compare it to the y test.
and usually, e is assumed to be zero.

## Multiple Linear Regression

is an extension of simple linear regression. have more than one independent variable or predictor.

MLR make things little bit complicated. infact there will be/create relationship between variables that might affecting prediction.  
MLR may address some issue:
1. overfitting
2. multirelationship among variables

general formula :  
y = b0 + b1x1 + b2x2 +.... +e  
y_hat = y = b0 + b1x1 + b2x2 +.... 

The multiple regression model is based on the following assumptions:

- There is a linear relationship between the dependent variables and the independent variables.  
- The independent variables are not too highly correlated with each other.  
- yi observations are selected independently and randomly from the population.  
- Residuals should be normally distributed with a mean of 0 and variance σ.  

### Evaluation Metrics

most common evaluation metrics for regression:
1. Mean Absolute error
2. Mean Square Error
3. Root Mean Square Erro

1. Mean Absolute Error
- easy to understand
- average of all predicted rows
- wont punish large error, see anscombe's quartet

2. Mean Square Error
- punish more large error 
- avoid anscombe quartet
- hard to interpret

3. Root Mean Square Error
- fix MSE y value
- fix punished large value

### Context of Performance Error

### Separate Residual

often it is a good idea to separate residual into new column or separated data. recall that residual is (y - y_hat) true y test value substracted by y prediction. this is why
1. determine linear regression is appropriate or not in our dataset
> famous anscombe quartet is not valid for linear regression, this is why residual plot comes in handy to judge that  

2. not matter how many feature do you have, plotting residual will give insight

Plot residual error to:
1. distribution plot, on its residual column
2. scatter plot, on true y test value

residual error should be random and close to normal distribution with mean close to zero.  
because we want them to be close to zero which mean our prediction is more accurate

when plotting residual error against y true value, we set red line on 0 y axis.
the perfect fit condition is when your residual datapoint is on red line or nearby it. also, it is not creating a pattern

## Interpreting Beta Coef

### Interpret Coefisien

Interpreting the coefficients:

---
* Holding all other features fixed, a 1 unit (A thousand dollars) increase in TV Spend is associated with an increase in sales of  0.045 "sales units", in this case 1000s of units . 
* This basically means that for every $1000 dollars spend on TV Ads, we could expect 45 more units sold.
----

---
---
* Holding all other features fixed, a 1 unit (A thousand dollars) increase in Radio Spend is associated with an increase in sales of  0.188 "sales units", in this case 1000s of units . 
* This basically means that for every $1000 dollars spend on Radio Ads, we could expect 188 more units sold.
----
----

* Holding all other features fixed, a 1 unit (A thousand dollars) increase in Newspaper Spend is associated with a **decrease** in sales of  0.001 "sales units", in this case 1000s of units . 
* This basically means that for every $1000 dollars spend on Newspaper Ads, we could actually expect to sell 1 less unit. Being so close to 0, this heavily implies that newspaper spend has no real effect on sales.
---
---

**Note! In this case all our units were the same for each feature (1 unit = $1000 of ad spend). But in other datasets, units may not be the same, such as a housing dataset could try to predict a sale price with both a feature for number of bedrooms and a feature of total area like square footage. In this case it would make more sense to *normalize* the data, in order to clearly compare features and results. We will cover normalization later on.**

## Polynomial Regression

polynomial is an enhancement of linear regression to maximize its performance.  
the main idea why using polynomial regression is trying to reveal potential relationship between predictor variables.  
this called interaction terms  
or sometimes our model is not perform best fit to data which resulting less precision prediction (high bias).  
when data behave like logistic equation (not actually logistic, but behave like that) we need more powerful model to fit the data at its best.  
according to explanation above, this is why polynomial regression comes in handy

remember, not all dataset can be applied with polynomial

polynomial equation :  
$$\hat{y} = \beta_0 + \beta_1x_1 + \epsilon $$

and create more features from the original x feature for some *d* degree of polynomial.

$$\hat{y} = \beta_0 + \beta_1x_1 + \beta_1x^2_1 +  ... + \beta_dx^d_1 + \epsilon$$


this might seems identical to multiple regression formula, but this is not the same.  
one of the main actor here is polynomial degree (d).
default degree in sklearn is 2, which means in example of 2 variables (a and b) resulting feateures:  
$$[1, a, b, a^2, ab, b^2] $$

since only x is being squared, polynomial still considered as linear regression

### Issue of Polynomial

this might address to us:
1. overfitting
2. not creating useful prediction

### Implementing Polynommial

Data science path lesson.ipynb

## Overfitting Model

1. the model fit too much noise in the data
2. this often results in low error on training set but high error on test/ validation sets
3. this might perform well in the training data, but it is a huge problem in test/ unseen data

## Underfitting Model

1. model doesnt fit the data well enough
2. low variance but high bias
3. simple model often resulting an underfit
4. generalize too much
5. poor performance in training and test sets

## Choosing best degree of Polynomial

in theory, more degree means more fit and capture data noise in detailed manner.  
but this could be dangerous and very poor performance with unseen data.

choosing perfect degree in polynomial is necessarry to get best fit, low bias, and can predict well for upcoming unseen data.

---
---
## Choosing a Model

### Adjusting Parameters

Are we satisfied with this performance? Perhaps a higher order would improve performance even more! But how high is too high? It is now up to us to possibly go back and adjust our model and parameters, let's explore higher order Polynomials in a loop and plot out their error. This will nicely lead us into a discussion on Overfitting.

Let's use a for loop to do the following:

1. Create different order polynomial X data
2. Split that polynomial data for train/test
3. Fit on the training data
4. Report back the metrics on *both* the train and test results
5. Plot these results and explore overfitting

## Regularization

regularization seek to solve few common model issue by:
1. minimizing model complexity
2. penalzing the loss function
3. reduc model overfitting (add more bias to reduce model variance)

Regularization purpose is reduce model overfitting by requiring :
1. more bias
2. more search for hyperparams penalty

3 main types of regularization: 
1. L1
> lasso regression
2. L2
> ridge regression
3. L1 and L2 combined
> elastic net

L1 Regularization or Lasso regression.
- limit the size of the coefficient
- can yield sparse model where some coef can be zero

with some features can become zero, you can decide which features is to be considered in regards to your model output.

formula :
RSS + lambda(sum of beta coef)  
RSS = Residual sum of square

### Common terms in ML

MSE = Mean square error  
RSS = residual sum of square

error and residual are different.  
error is the difference between y prediction against y true  
residual is the difference of y against model line

## L2 or Ridge Regression

add penalty equal to the square of the magnitude of coef.  
- all coef are shrunk by the same factor
- doesnt necessarily eliminate the coef

formula :  
RSS + lambda (sum of beta coef^2)

## Elastic Net

combined L1 and L2 with an addition of alpha that deciding portion of them.  
alpha is between 0-1

## Feature Scaling

feature scaling provides many benefits to our machine learning process.  
some machine learning models that rely on distance metrics require scaling to perform well  
