In [1]:
%config Completer.use_jedi = False

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv('C:\\Users\\ACER\\Data science path\\Jose lesson\\08-Linear-Regression-Models\\Advertising.csv')

In [4]:
X = df.drop('sales',axis=1)
y = df['sales']

In [5]:
from sklearn.linear_model import LinearRegression

In [7]:
model_wo_train = LinearRegression()
model_wo_train.fit(X,y)

LinearRegression()

In [8]:
X_new = [[180,110,50]]

In [20]:
rough_pred = model_wo_train.predict(X_new)
rough_pred

array([31.86295276])

### with train test 

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=100)

In [14]:
model_w_train = LinearRegression()
model_w_train.fit(X_train,y_train)

LinearRegression()

In [18]:
trained_pred = model_w_train.predict(X_test)
trained_pred

array([10.62160072, 20.00625302, 16.91850882, 19.17040746, 20.94974131,
       13.12284284, 11.80740696, 12.32019766, 20.57806782, 20.95662688,
       10.79096475, 19.54868702,  6.42403866, 15.23133391,  8.97226257,
        7.89897862, 16.23599497, 12.02636477, 17.09702178, 11.26080277,
       16.97826292,  9.75655721, 20.82389762, 17.20916742, 15.13816239,
       21.97290698, 19.20181841, 10.07501899, 19.39017185, 14.8673761 ,
       14.36798893,  7.55604543,  9.96742165, 14.76342565,  7.20995576,
       13.60003295,  7.49088656, 11.70865932, 13.46091883, 15.2229793 ,
       17.18088277, 13.56738329, 14.30942267, 13.72909849, 11.88559349,
        8.77039705, 12.1244102 , 19.20252289,  9.08376601,  5.15367352,
       16.22852749, 18.14111213, 12.94835466, 16.86274503, 17.86462435,
       12.33930625,  4.3575739 , 11.25904494, 16.11560622, 13.56602169])

In [26]:
from sklearn.metrics import mean_absolute_error as MAE,mean_squared_error as MSE

In [28]:
MAE_result = MAE(y_test,trained_pred)
MAE_result

1.0638483124072022

In [30]:
RMSE = np.sqrt(MSE(y_test,trained_pred))
RMSE

1.3603977338130544

In [25]:
model_w_train.predict(X_new)

array([31.93290094])